version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # ou le chemin vers requirements.txt
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"  # ou le chemin vers package.json
    schedule:
      interval: "weekly"
